#!/bin/bash

WIDTH=1920
HEIGHT=1080

for FILENAME in "$@" ;

do

FILEBASE=${FILENAME%.*}

if [ -e "$FILEBASE.meta" ]
then META="-i '$FILEBASE.meta' -map_metadata 0:1"
else META=''
fi

ffmpeg -i \'$FILENAME\' $META -acodec libfaac -ab 192k -s $WIDTH\x$HEIGHT -aspect 16:9 -vcodec libx264 -pix_fmt yuv420p -profile:v main -r 30000/1001 -crf 20 -threads 0 \'$FILEBASE.temp.mp4\'

qt-faststart \'$FILEBASE.temp.mp4\' \'$FILEBASE.$WIDTH\x$HEIGHT.mp4\'

rm \'$FILEBASE.temp.mp4\';

done
